<?php

namespace App\Repository;

use App\Entity\Person\Person;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

class PersonRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Person::class);
    }

    /**
     * @return array Person
     */
    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $cadena
     * @return array Person
     */
    public function findByEmail($cadena)
    {
        return $this->createQueryBuilder('g')
            ->where('g.email = :value')->setParameter('value', $cadena)
            ->orderBy('g.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * @param Person $person
     */
    public function save(Person $person)
    {
        $this->getEntityManager()->persist($person);
        $this->getEntityManager()->flush();
    }
}
