<?php

namespace App\Repository;

use App\Entity\Person\Person;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

class PersonRepository extends ServiceEntityRepository implements UserLoaderInterface
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Person::class);
    }

    /**
     * @return array Person
     */
    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $cadena
     * @return array Person
     */
    public function findByEmail($cadena)
    {
        return $this->createQueryBuilder('g')
            ->where('g.email = :value')->setParameter('value', $cadena)
            ->orderBy('g.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * @param Person $person
     */
    public function save(Person $person)
    {
        $this->getEntityManager()->persist($person);
        $this->getEntityManager()->flush();
    }

    public function loadUserByUsername($email)
    {
        return $this->createQueryBuilder('p')
            ->where('p.email = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
